### ISSUE TITLE
Error: Chain broke on AT+HTTPDATA=16,5000

### ISSUE THREAD

**Issue by davidhq** [heikki/tessel-tracker-demo#1]
Thank you for this example...

looks nice but I have some problems...

My code here: [removed]

produces the error `Error: Chain broke on AT+HTTPDATA=16,5000`

basic gprs example (sending text) works...

Any ideas what could I try to fix this?

PS: my APN is correct (`internet`)

thank you
david

**Comment by heikki** [comment]
@davidhq Compare your gist with the example code again.

Some problems I spotted right away:
- you don't call `initialize()` anywhere
- there's no `post` function defined even though you refer to it in two places

**Comment by davidhq** [comment]
@heikki: OH! Not sure how I managed to do two such fails :)

I now fixed it: https://gist.github.com/davidhq/e9d52f3cad4a33dedf12

and it worked once:

```
GPRS module connected to Tessel. Searching for network...
Error: Chain broke on AT+HTTPDATA=16,5000
Error: Postmaster busy
sent post req
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: Postmaster busy
sent post req
```

So here it worked (sent two requests) - I saw them in `requestbin` but still there were errors in between..

On the next run with the same code it didn't send a successful request:

```
GPRS module connected to Tessel. Searching for network...
Error: Postmaster busy
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: Postmaster busy
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: Postmaster busy
```

Am I still doing something wrong? It would be great if this was reliable and deterministic..

thank you
david

**Comment by heikki** [comment]
Try removing [lines 70 & 71](https://gist.github.com/davidhq/e9d52f3cad4a33dedf12#file-gprs-js-L70-L71). Once `initialize` is succesful it will call `post` on [line 44](https://gist.github.com/davidhq/e9d52f3cad4a33dedf12#file-gprs-js-L44).

Reliability was and is still a problem. :)

**Comment by davidhq** [comment]
OK thank you!

It seems to work quite ok now but something is still strange, I see the requests so not sure why it's reporting error:

```
GPRS module connected to Tessel. Searching for network...
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
Error: no reply after 32000 ms to message "AT+HTTPACTION=1"
```

So [L62](https://gist.github.com/davidhq/e9d52f3cad4a33dedf12#file-gprs-js-L62) is called... all good but as I said the request actually goes through .. (and [L64](https://gist.github.com/davidhq/e9d52f3cad4a33dedf12#file-gprs-js-L64) is never called)

**Comment by davidhq** [comment]
I noticed something else... one request is sent approx once in 30s and exactly that much is the set timeout in `.setHttpParameter('TIMEOUT', '30')` ... Also strange... I think one post request should be sent every 0.5s as per [L67](https://gist.github.com/davidhq/e9d52f3cad4a33dedf12#file-gprs-js-L67) `setTimeout(post, 500);`

**Comment by heikki** [comment]
As I said earlier: try removing lines [70 & 71](https://gist.github.com/davidhq/e9d52f3cad4a33dedf12#file-gprs-js-L70-L71).
